# This config file for Travis CI utilizes ros-industrial/industrial_ci package.
# For more info for the package, see https://github.com/ros-industrial/industrial_ci/blob/master/README.rst

sudo: required
dist: trusty
services:
  - docker
language: generic
python:
  - "3.8"
compiler:
  - gcc
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - ronaldsonbellande@gmail.com
env:
  matrix:
    - ROS_DISTRO=noetic ROS_REPO=ros-shadow-fixed UPSTREAM_WORKSPACE=debian
branches:
  only:
    - master
    - noetic
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script:
  - source .ci_config/travis.sh
  
